<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AutoReport.Core/AutoReport.Core.csproj" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Xml.Linq" />
  </ItemGroup>
</Project>
