<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Reference Include="System.Drawing" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Xml.Linq" />
  </ItemGroup>
</Project>
